spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

info:
  app:
    name: "gatewayserver"
    description: "PressTwo Gateway Server Application"
    version: "1.0.0"