build:
  version: "3.0"

input:
  message: "Welcome to PressTwo stata related docker APIs "
  contactDetails:
    name: " - Developer"
    email: "common@presstwo.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345