server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
       native:
        search-locations: "classpath:/config"

