apiVersion: apps/v1
kind: Deployment
metadata:
  name: input-deployment
  labels:
    app: input
spec:
  replicas: 1
  selector:
    matchLabels:
      app: input
  template:
    metadata:
      labels:
        app: input
    spec:
      containers:
        - name: input
          image: presstwo/input:s1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: presstwo-configmap
                  key: INPUT_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: presstwo-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: presstwo-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: presstwo-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: presstwo-configmap
                  key: SPRING_RABBITMQ_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: input
spec:
  selector:
    app: input
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080