server:
  port: 8080
spring:
  application:
    name: "input"
  profiles:
    active: "prod"
  datasource:
    url:
    driverClassName:
    username:
    password:
  jpa:
    database-platform:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "PressTwo Input Application"
    version: "1.0.0"

