server:
  port: 8080
spring:
  application:
    name: "input"
  profiles:
    active: "prod"
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: input

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "input"
    description: "PressTwo Input Application"
    version: "1.0.0"

